# Generated by Django 5.0 on 2023-12-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('material', models.CharField(max_length=20, verbose_name='Материал')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('count', models.PositiveIntegerField(verbose_name='Количество')),
                ('produced', models.CharField(max_length=20, verbose_name='Произведён')),
            ],
        ),
    ]
